default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: gifts_api

test:
  <<: *default
  database: gifts_api_test

production:
  <<: *default
  database: gifts_api